name: livekit_manager
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'


dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9

  image_multi_type: ^1.0.5

  m_cubit:
#    path: ../../../packages/m_cubit
    git:
      url: https://github.com/saedAlHanash/m_cubit

  flutter_bloc: ^9.1.1
  logger: ^2.7.0
  #  persistent_bottom_nav_bar_v2: ^5.4.0
  pull_to_refresh: ^2.0.0
  intl_utils: ^2.8.14
#  flutter_local_notifications: ^19.4.2
  shared_preferences: ^2.5.5
  collection: ^1.19.1
  flutter_screenutil: ^5.9.3
  dropdown_button2: ^3.1.0
  awesome_dialog: ^3.3.0
  carousel_slider: ^5.1.2
  http: ^1.6.0
  intl: ^0.20.2
  go_router: ^17.3.0
  get_it: ^9.2.1
  group_button: ^5.3.4
  livekit_client: ^2.8.0
  permission_handler: ^12.0.1
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  file_picker: ^8.0.0

  drawable_text: ^1.0.0
  flutter_background: ^1.3.1
  top_snackbar_flutter: ^3.3.0
  audioplayers: ^6.7.1
  signalr_core_new: ^1.0.3
  lottie: ^3.3.3
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/
    - assets/sounds/

  #  fonts:
  #    - family: regular
  #      fonts:
  #        - asset: assets/fonts/Tajawal-Regular.ttf
  #    - family: semeBold
  #      fonts:
  #        - asset: assets/fonts/Tajawal-Medium.ttf
  #    - family: bold
  #      fonts:
  #        - asset: assets/fonts/Tajawal-Bold.ttf
  #
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
    - family: semeBold
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf


flutter_intl:
  enabled: true
