name: livekit_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  flutter_background: ^1.3.0+1
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  logging: ^1.3.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.1
  flutter_svg: ^2.2.1
  dropdown_button2: ^2.3.9
  collection: '>=1.16.0'

  livekit_client: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/logo-dark.svg
